version: '3'

services:
  redis:
    image: "redis:alpine"
    container_name: "redis_server_pubsub"
    restart: unless-stopped
    volumes:
      - ./redis:/data
    ports:
      - 127.0.0.1:6379:6379
